##Numpy

[Numpy](http://www.numpy.org/) 是一个Python扩展软件包，主要用于科学计算。它提供了高性能的数据结构，可以有效地处理多维数组和矩阵，也称为“面向数组的计算”。另外，NumPy提供用于操作这些数组的高级数学函数。

NumPy不包含在默认Python中。 用户可以通过[Python软件包索引](https://pypi.org/) 进行安装，例如`pip install numpy`或者`conda install -n my_project numpy`，`my_project`为虚拟环境名称。

要使用NumPy，请使用import将NumPy导入：

In [1]:
import numpy as np

a=np.zeros(10)

a


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

------

### 创建NumPy数组
* 使用`array`函数，基于列表和元组手动创建数组：

In [2]:
a = np.array([1, 2, 3, 4])  # from list
b = np.array((5.6, 6.7, 7.8, 8.9, 9.))  # from tuple
print(a)
print(b)
print(a.ndim)  # 1D array
print(a.shape)
print(a.size)
print(a.dtype)

[1 2 3 4]
[5.6 6.7 7.8 8.9 9. ]
1
(4,)
4
int32


查看数据类型:

In [3]:
type(a), type(b)

(numpy.ndarray, numpy.ndarray)

创建二位数组：

In [4]:
c = np.array([[1., 2., 3., 4.], [5., 6., 7., 8.]])
print(c)
print(c.ndim)  # 2D array
print(c.shape)  # the shape is 2 x 4
print(c.size)
print(c.dtype)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
2
(2, 4)
8
float64


在创建的时候数据类型可以指定：

In [5]:
d = np.array([[1, 2, 3], [10, 20, 30]], dtype='float64')
print(d.dtype)

float64


* 使用其它函数创建数组：

	`np.arange()` 和 `np.linspace()` 通常用于创建元素间间隔相等的数组. 前者需要指定初始值、结束值和步进，后者则需要给定初始值、结束值和元素的个数。

In [6]:
# In practice, we rarely enter elements one by one.
e = np.arange(6)  # from 0 to n-1 with an increment of 1
print(e)

# Or specify the start, end and increment values
f = np.arange(2, 10, 2)
print(f)

# Or use the linspace function that is similar to that of Matlab
g = np.linspace(2, 13, 12)  # start, end and number of elements
print(g)

[0 1 2 3 4 5]
[2 4 6 8]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]


一位数组可以转换成多维数组，转换过程中需确保元素的个数相等。

In [7]:
h = g.reshape([2, 6])  # 2D
print(h)
print('\n\n')

i = g.reshape([2, 2, 3])  # 3D
print(i)

[[ 2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13.]]



[[[ 2.  3.  4.]
  [ 5.  6.  7.]]

 [[ 8.  9. 10.]
  [11. 12. 13.]]]


 `np.ones()`, `np.zeros()`, `np.random()`, `np.empty()` 和 `np.full()` 通常用于创建尺寸已知的数组。

In [8]:
# Create an array of ones
print('np.ones():\n', np.ones((2, 3)), '\n')

# Create an array of zeros
print('np.zeros():\n', np.zeros((2, 3, 4), dtype=np.int32), '\n')

# Create an array with random values
print('np.random():\n', np.random.random((2, 2)), '\n')

# Create an empty array that has a shape of 3x2
print('np.empty():\n', np.empty((3, 2)), '\n')

# Create a full array that has a shape of 3x2 and is filled with number 10
print('np.full():\n', np.full((3, 2), 10), '\n')

np.ones():
 [[1. 1. 1.]
 [1. 1. 1.]] 

np.zeros():
 [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]] 

np.random():
 [[0.62065441 0.35174786]
 [0.90845371 0.39471633]] 

np.empty():
 [[1. 1.]
 [1. 1.]
 [1. 1.]] 

np.full():
 [[10 10]
 [10 10]
 [10 10]] 



`np.eye()` 用于创建单位矩阵，`np.diag()` 用于创建对角矩阵。

In [9]:
print('np.eye():\n', np.eye(3), '\n')

print('np.diag():\n', np.diag((2, 3, 4, 5)))

np.eye():
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

np.diag():
 [[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


`np.mgrid()` 创建一个二维的网格矩阵，类似“meshgrid”。

In [10]:
x, y = np.mgrid[0:4, 1:6]
print('x: \n', x, '\n')
print('y: \n', y, '\n')

x: 
 [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]] 

y: 
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]] 



------

### Indexing and slicing

Numpy数组元素的访问和列表类似，用方括号表示，第一个元素的索引号为0，同时也支持负的索引号。也可用切片的方式访问多个元素。

In [11]:
a = np.arange(10)
print('Array a: ', a[:])
print('The first element of a: ', a[0])
print('The last element of a: ', a[-1])
print('The first 3 elements of a: ', a[:3])
print('The last 3 elements of a: ', a[-3:])
print('Elements from the third to the end: ', a[2:])
print('Elements from the third to the eighth: ', a[2:8])
print('Elements from the start to the end with a step of 1: ', a[::])
print('Elements from the start to the end with a step of 2: ', a[::2])
print('Elements from the third to the eighth with a step of 2: ', a[2:8:2])

Array a:  [0 1 2 3 4 5 6 7 8 9]
The first element of a:  0
The last element of a:  9
The first 3 elements of a:  [0 1 2]
The last 3 elements of a:  [7 8 9]
Elements from the third to the end:  [2 3 4 5 6 7 8 9]
Elements from the third to the eighth:  [2 3 4 5 6 7]
Elements from the start to the end with a step of 1:  [0 1 2 3 4 5 6 7 8 9]
Elements from the start to the end with a step of 2:  [0 2 4 6 8]
Elements from the third to the eighth with a step of 2:  [2 4 6]


与列表不同的是，多维数组元素的访问通过给定每一维上的索引号：

In [12]:
# Here we use list comprehension to construct a 2-D array
b = np.array([[m + n for m in np.arange(6)] for n in np.arange(4)])
print('Array b:\n', b[:, :], '\n')
print('The second row: ', b[1, :], '\n')
print('A subset of array b:\n', b[1:4, 2:4])

Array b:
 [[0 1 2 3 4 5]
 [1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]] 

The second row:  [1 2 3 4 5 6] 

A subset of array b:
 [[3 4]
 [4 5]
 [5 6]]


多维数组中若要访问某一维全部的数据，使用 `:`代替索引号或者省略：

In [13]:
print('The first row: ', b[0])  # equivalent to b[0, :]

The first row:  [0 1 2 3 4 5]


索引号可以是列表：

In [14]:
idx_row = np.array([0, 2, 3])
idx_col = np.array([1, 3, 5])
print('b[idx_row]:\n', b[idx_row], '\n')
print('b[idx_col]:\n', b[:, idx_col], '\n')
print('b[idx_row, idx_col]:\n', b[idx_row, idx_col])

b[idx_row]:
 [[0 1 2 3 4 5]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]] 

b[idx_col]:
 [[1 3 5]
 [2 4 6]
 [3 5 7]
 [4 6 8]] 

b[idx_row, idx_col]:
 [1 5 8]


使用逻辑掩码作为NumPy的索引号对于选择性地访问和处理数组元素非常有用。我们可以将bool数据类型的数组用作索引号，并选择其索引值为true的元素。

In [15]:
masks = np.array([[0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1]], dtype=bool)
print('b:\n', b, '\n')
print('masks:\n', masks, '\n')
print('Masked b:\n', b[masks])

b:
 [[0 1 2 3 4 5]
 [1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]] 

masks:
 [[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]] 

Masked b:
 [1 3 5 2 4 6 3 5 7 4 6 8]


逻辑判断作为索引号也非常的有用。数组中的每个元素将做逻辑判断，然后返回逻辑为真的元素，例如提取大于2的元素。

In [16]:
b[b > 2]

array([3, 4, 5, 3, 4, 5, 6, 3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 8])

------

### 运算
#### 算数运算
`+`, `-`, `*` 和 `/`为加减乘除运算，可以是两个数组或者一个数组与一个标量。记住，算术运算是按元素的运算（element-wise）：

In [17]:
a = 10.5
array1 = np.array([[m + n for m in np.arange(6)] for n in np.arange(4)], dtype=np.float32)  # 4 x 6 2D arrays
array2 = np.array([[m - n for m in np.arange(6)] for n in np.arange(4)], dtype=np.float32)  # 4 x 6 2D arrays

In [18]:
print(array1 + a, '\n')
print(array1 - array2, '\n')
print(array1 / a, '\n')
print(array1 * array2)

[[10.5 11.5 12.5 13.5 14.5 15.5]
 [11.5 12.5 13.5 14.5 15.5 16.5]
 [12.5 13.5 14.5 15.5 16.5 17.5]
 [13.5 14.5 15.5 16.5 17.5 18.5]] 

[[0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4. 4.]
 [6. 6. 6. 6. 6. 6.]] 

[[0.         0.0952381  0.1904762  0.2857143  0.3809524  0.47619048]
 [0.0952381  0.1904762  0.2857143  0.3809524  0.47619048 0.5714286 ]
 [0.1904762  0.2857143  0.3809524  0.47619048 0.5714286  0.6666667 ]
 [0.2857143  0.3809524  0.47619048 0.5714286  0.6666667  0.7619048 ]] 

[[ 0.  1.  4.  9. 16. 25.]
 [-1.  0.  3.  8. 15. 24.]
 [-4. -3.  0.  5. 12. 21.]
 [-9. -8. -5.  0.  7. 16.]]


`+=`, `-=`, `*=` and `/=` 与上述常规操作不同，此操作发生在本地进而修改当前的数组，而不是创建新的数组。

In [19]:
array3 = np.array(np.arange(10), dtype=float)
print(array3)
array3 += 2.5
print(array3)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5]


#### 线性代数运算

数组操作不是矩阵操作。前者是基于元素的运算，而后者则遵循线性代数的数学规则。如果我们将NumPy数组用作线性代数的运算（例如，点乘np.dot（）），则两个数组的形状应与数学规则匹配。

In [20]:
import numpy as np
A = np.array([[m + n for m in np.arange(4)] for n in np.arange(4)])  # 4 x 4 2D arrays
B = np.array([[m - n for m in np.arange(3)] for n in np.arange(4)])  # 4 x 3 2D arrays
C = np.arange(4)  # 1D vector with a size of 4
A, B, C
print(A)
print(B)
print(C)
print(A.shape)
print(B.shape)
print(C.shape)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]
 [-3 -2 -1]]
[0 1 2 3]
(4, 4)
(4, 3)
(4,)


In [21]:
print(np.dot(A, B), '\n')
print(np.dot(A, C))

[[-14  -8  -2]
 [-20 -10   0]
 [-26 -12   2]
 [-32 -14   4]] 

[14 20 26 32]


或者使用 `np.matrix()`函数创建一个矩阵：

In [22]:
AM = np.matrix(A)
BM = np.matrix(B)
CM = np.matrix(C)
AM, BM, CM

(matrix([[0, 1, 2, 3],
         [1, 2, 3, 4],
         [2, 3, 4, 5],
         [3, 4, 5, 6]]),
 matrix([[ 0,  1,  2],
         [-1,  0,  1],
         [-2, -1,  0],
         [-3, -2, -1]]),
 matrix([[0, 1, 2, 3]]))

然后 `+`, `-`, 和 `*`的运算将遵循线性代数，而不是按元素。

In [23]:
# dot product
AM * BM

matrix([[-14,  -8,  -2],
        [-20, -10,   0],
        [-26, -12,   2],
        [-32, -14,   4]])

In [24]:
AM * CM.T  # here .T means Transport that converts CM to a column vector

matrix([[14],
        [20],
        [26],
        [32]])

In [25]:
# inner product
CM * CM.T  # you can also use np.inner() function

matrix([[14]])

In [26]:
# outer product
CM.T * CM  # you can also use np.outer() function

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [27]:
# Matrix addition
CM.T + AM * CM.T

matrix([[14],
        [21],
        [28],
        [35]])

举证的行列式和逆矩阵：

In [28]:
# Determinant
M = np.array([[6, 1, 2], [2, -4, 6], [3, 5, 8]])
np.linalg.det(M)

-326.0

In [29]:
# Inverse
np.linalg.inv(M)

array([[ 0.19018405, -0.00613497, -0.04294479],
       [-0.00613497, -0.12883436,  0.09815951],
       [-0.06748466,  0.08282209,  0.0797546 ]])

#### 其它常用函数：

Numpy还提供了大量的数学函数，如统计学函数 `np.sum()`, `np.mean()`, `np.min()`, `np.max()`, `np.std()`, `np.var()`, `np.prod()`, and `np.trace()`和三角函数。完整的数学函数的列表： [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html).

------

### Copies and Views

Python中的内存处理通常很麻烦。对于数组操作，有些操作会将数组数据复制到新数组，有些则不然。尤其是对于初学者来说，很容混淆。让我们看看什么是 _copies_ 和 _views_。

#### No copy

数组赋值通常不会复制数组数据，只是给数组另一个变量名。对新数组所做的更改将传递到原始数组。

In [30]:
D = np.array([1, 2, 3, 4, 5])
D

array([1, 2, 3, 4, 5])

In [31]:
D1 = D
D1 is D

True

In [32]:
D1[0:2] = 100  # we change D1
print(D)  # D is also changed

[100 100   3   4   5]


记住，将一个可变异的参数作为函数的输入的时候，所传递的是reference，函数内若对传递的参数进行了修改，函数外被传递的参数的值也将被修改。可以理解为函数参数实际上传递的只是参数的名字。

In [33]:
def myfunc(a):
    a[:] = -10

myfunc(D)
D

array([-10, -10, -10, -10, -10])

#### View and shallow copy

不同的数组可以共享相同的数据（相同的内存），并以不同的形式（例如不同的尺寸数）表示相同的数据。 这个称为`view`。

In [34]:
E = np.array([1, 2, 3, 4, 5, 6])
E

array([1, 2, 3, 4, 5, 6])

In [35]:
E1 = E.view()
E1

array([1, 2, 3, 4, 5, 6])

In [36]:
E1 is E

False

In [37]:
E1.shape = (3, 2)  # now E1's shape is 3x2
E1.shape

(3, 2)

In [38]:
E.shape

(6,)

In [39]:
E1[0, :] = 0  # Now we change E1
E  # E is also changed

array([0, 0, 3, 4, 5, 6])

记住，切片操作返回一个`view`。

In [40]:
E2 = E[2:]
E2

array([3, 4, 5, 6])

In [41]:
E2[:] = 0  # change E2
E  # E also changed

array([0, 0, 0, 0, 0, 0])

#### Deep copy
真正的copy：

In [42]:
E3 = E.copy()
E3

array([0, 0, 0, 0, 0, 0])

In [43]:
E3[:] = 100  # E3 has been changed
E  # E is not affected

array([0, 0, 0, 0, 0, 0])

为组织函数改变一个数组的值，通常可以将一个数组的copy传递给函数，但是更耗内存。

In [44]:
myfunc(E.copy())
E

array([0, 0, 0, 0, 0, 0])

In [45]:
# If we pass E directly to the function
myfunc(E)
E

array([-10, -10, -10, -10, -10, -10])

------

### 数组的操作
#### Flattening, reshaping and resizing
使用`flatten` 或者 `ravel`函数可以将任意一个多维数组可以转变成一个一维数组。 前者返回一个copy或者返回view。

In [46]:
A

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [47]:
A1 = A.flatten()
A1

array([0, 1, 2, 3, 1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6])

In [48]:
# change A1
A1[1:6] = 99
A1

array([ 0, 99, 99, 99, 99, 99,  3,  4,  2,  3,  4,  5,  3,  4,  5,  6])

In [49]:
# verify A
A

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [50]:
A2 = A.ravel()
A2[1:6] = 99  # we change A2
A  # A is changed

array([[ 0, 99, 99, 99],
       [99, 99,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6]])

np.reshape可改变数组维上的尺寸，返回的是view。尺寸改变前后数组的尺寸应保持一致，例如，数组A有16个元素，我们可以将其重构为`（4，4）`，`（2，8）`或`（2，2，4）`，而不是`（3，4）`， `（3，4）`或其他与数组大小不匹配的尺寸。

In [51]:
A3 = A.reshape(2, 8)
A3

array([[ 0, 99, 99, 99, 99, 99,  3,  4],
       [ 2,  3,  4,  5,  3,  4,  5,  6]])

In [52]:
# let's introduce changes to A3
A3[0, 1:6] = 100
A

array([[  0, 100, 100, 100],
       [100, 100,   3,   4],
       [  2,   3,   4,   5],
       [  3,   4,   5,   6]])

In [53]:
A4 = np.reshape(A, (2, 8))
A4

array([[  0, 100, 100, 100, 100, 100,   3,   4],
       [  2,   3,   4,   5,   3,   4,   5,   6]])

In [54]:
A4[0, 1:6] = 200
A

array([[  0, 200, 200, 200],
       [200, 200,   3,   4],
       [  2,   3,   4,   5],
       [  3,   4,   5,   6]])

也可以使用数组自带的方法进行本地操作：

In [55]:
A.shape = (2, 8)
A

array([[  0, 200, 200, 200, 200, 200,   3,   4],
       [  2,   3,   4,   5,   3,   4,   5,   6]])

resize函数：

In [56]:
F = np.array([[m + n + 1 for m in np.arange(3)] for n in np.arange(5)])  # 5 x 3 2D arrays with a size of 15
F.resize(20)  # we change the size from 15 to 20
F

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6, 5, 6, 7, 0, 0, 0, 0, 0])

在resize的操作中，如果新的尺寸大于原始的尺寸，多余的元素将用`0`填补。

#### Array axis
对于多维数组，NumPy允许用户对特定轴（维）进行操作。

In [57]:
F = np.array([[m + n + 1 for m in np.arange(3)] for n in np.arange(5)])
F

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [58]:
F.sum(axis=1)

array([ 6,  9, 12, 15, 18])

可以通过添加一个新的轴来升级数组的维数，如一维数组提升到2维数组，如下面的5个元素的一维数组被提升为5x1的二维数组。

In [59]:
F = np.array([1, 2, 3, 4, 5])
F

array([1, 2, 3, 4, 5])

In [60]:
F.shape

(5,)

In [61]:
F[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [62]:
F[:, np.newaxis].shape

(5, 1)

#### Stacking, splitting and repeating arrays
使用`vstack`、`hstack` 和 `concatenate` 函数可以将多个数组沿不同的轴堆叠起来。 `vstack` 和 `hstack` 分别用来将两个数组沿竖直方向和水平方向堆叠起来。`concatenate` 用来在指定的轴（维）上堆叠数组。

In [63]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[10, 20, 30], [40, 50, 60]])
np.vstack([a, b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [64]:
np.hstack([a, b])

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [65]:
np.concatenate((a, b), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [66]:
np.concatenate((a, b), axis=1)

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

同样的，可以使用`vsplit` 和 `hsplit`函数将一个数组分裂成多个尺寸相等的数组。

In [67]:
np.vsplit(a, 2)  # split into 2 arrays

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [68]:
np.hsplit(a, 3)  # split into 3 arrays

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [69]:
np.hsplit(a, (1, 2))  # split after the first and second column

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

使用`repeat` 和 `tile` 函数可以通过堆叠重复的数组组成更大的新数组。

In [70]:
np.repeat(a, 3)  # Repeat a by 3 times

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [71]:
np.tile(a, 3)  # 3 tiles

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [72]:
# clone a row vector 3 times to form a 2D array
b = np.array([1, 2, 3, 4, 5])
np.repeat(b[np.newaxis, :], 3, 0)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [73]:
# Or use the tile function
np.tile(b, (3, 1))  # repeat b 3 times in row and 1 in column

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

#### Conditions
实际问题中经常会碰到有选择性的处理数组中的数据。`np.where`函数可以用来实现此操作。

In [74]:
c = np.array([[m + n + 1 for m in np.arange(8)] for n in np.arange(3)])
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10]])

In [75]:
# If 8 > value > 3, set value = 1;
c[np.where((c > 3) & (c < 8))] = 1
c

array([[ 1,  2,  3,  1,  1,  1,  1,  8],
       [ 2,  3,  1,  1,  1,  1,  8,  9],
       [ 3,  1,  1,  1,  1,  8,  9, 10]])

In [76]:
# another array that has the same shape
d = np.array([[m + n - 2 for m in np.arange(8)] for n in np.arange(3)])
d

array([[-2, -1,  0,  1,  2,  3,  4,  5],
       [-1,  0,  1,  2,  3,  4,  5,  6],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [77]:
# get the bigger elements of two arrays
np.where(c > d, c, d)  # if condition is true, take element from c, otherwise from d.

array([[ 1,  2,  3,  1,  2,  3,  4,  8],
       [ 2,  3,  1,  2,  3,  4,  8,  9],
       [ 3,  1,  2,  3,  4,  8,  9, 10]])

#### Broadcasting
Broadcasting 是Numpy的一个强大功能。如前所述，Numpy中的数组操作是按元素进行的，并且数组的尺寸大小需相同。但是，为了节省内存和方便计算，Numpy允许在一些特定规则下对不同大小的数组执行操作。这种操作称为_broadcasting_。它允许具有不同维度的数组可进行数学运算操作，如一个3x2的数组可以和一个1x2的数组相加。

若遵循以下两个规则，则可以进行Broadcasting操作：

*如果两个数组的维数不同（例如，形状（3，4）和形状（4）），则较小数组的维数将自动增加1，直到所有数组的维数相同（例如形状（4）->形状（1、4））

*上述操作是的两个数组的维数相等，但每个维数上的尺寸还不相等。第二步，针对较小数组，从尾部维数开始，与较大尺寸的数组进行比较，如果维度尺寸为1，则自动将该维度上的尺寸增加至与较大数组的尺寸相等

请看如下例子：

In [78]:
a1 = np.array([[m + n for m in np.arange(8)] for n in np.arange(3)])  # shape (3, 8)
a1

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8, 9]])

In [79]:
a2 = np.arange(8)  # shape (8,)
a2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [80]:
a1 + a2  # a1 and a2 have different shapes, but we can still perform operations

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15],
       [ 2,  4,  6,  8, 10, 12, 14, 16]])

为详细了解broadcasting的工作原理，我们将整个过程分步来实现，首先利用上述第一个规则：

In [81]:
a2 = a2[np.newaxis, :]  # see np.newaxis examples in previous sections
a2.shape

(1, 8)

通过添加一个轴（维），数组a2变成了二维数组，与a1一样了。但是每个维度上的尺寸是不一样的。接下来我们进行第二步操作。

从尾部维度开始比较，第一维度都是8。然后比较第二维度，a1是3，然后a2是1，其尺寸不同。为将a2的第一个轴的尺寸从变成3，我们用np.repeat()函数将数组沿着第一轴重复3次：

In [82]:
a2 = np.repeat(a2, 3, 0)
a2

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]])

In [83]:
# now a1 and a2 have the same shapes
a1 + a2

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15],
       [ 2,  4,  6,  8, 10, 12, 14, 16]])

#### Vectorisation（向量化）
向量化是NumPy中的核心要素。到目前为止，其实我们已经通过使用内置的NumPy函数（例如np.add（），np.dot（）和np.multiply（ ）`），它们的操作都是向量化操作。这些操作以元素方式进行，但是多个元素并列进行，进而加快速度。让我们比较一下逐个元素操作和向量化操作的性能区别，以$f(x, y) = x^2 + y^2$这个计算为例:

In [84]:
def python_f(x, y):
    return [x**2 + y**2 for (x, y) in zip(x, y)]


def numpy_f(x, y):
    return x**2 + y**2

接下来我们计算1000个数的平方和来测试下两种方法的速度：

In [85]:
# Python
x, y = range(1000), range(1000)
%timeit python_f(x, y)

371 µs ± 7.77 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [86]:
# NumPy
x, y = np.arange(1000), np.arange(1000)
%timeit numpy_f(x, y)

2.95 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


通过向量化for循环，NumPy版本的速度明显远快于Python的版本。所以，尽可能避免在Python中使用for循环来对大的数组进行计算和操作。除了向量化直接的算术运算外，我们还可以使用诸如np.where等之类的NumPy函数对具有条件逻辑的代码进行向量化，请参考以下示例：

In [87]:
# Python version
def python_f2(x, mask):
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if mask[i, j] > 0.6:
                x[i, j] = 1.
            elif mask[i, j] < 0.3:
                x[i, j] = -1.
            else:
                x[i, j] = 0.


# NumPy version
def numpy_f2(x, mask):
    x[np.where(mask > 0.6)] = 1.
    x[np.where(mask < 0.3)] = -1.
    x[np.where(np.logical_and(mask <= 0.6, mask >= 0.3))] = 0.

In [88]:
X = np.arange(100000).reshape(1000, 100)
mask = np.random.rand(1000, 100)
%timeit python_f2(X, mask)

37.8 ms ± 2.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [89]:
%timeit numpy_f2(X, mask)

2.39 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


上面描述的两个例子是相对简单的向量化例子，所要解决的问题相对简单且向量化很明显。但是，在许多实际情况下，问题的可向量化性是不明显的，这就需要用户带着向量化的思想重新审视问题，并重构解决问题的思路，或者通过使用其他算法或发明新算法使其可向量化。这不仅需要对NumPy有深刻的理解，还需要在解决此类问题上的大量实践经验。

让我们考虑一个相对复杂的计算问题：计算$A[i，j]\times i \times j$的总和，其中$A[i，j]$是2D数组，$i，j$是索引。简单的实现可以写成：

In [90]:
def python_f3(A):
    val = 0.
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            val += A[i, j] * i * j
    return val

In [91]:
A = np.arange(30000, dtype=np.float64).reshape(300, 100)
%timeit python_f3(A)

13.1 ms ± 448 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [92]:
def numpy_f3(A):
    idx_i = np.tile(np.arange(A.shape[0])[:, np.newaxis], (1, A.shape[1]))
    idx_j = np.tile(np.arange(A.shape[1]), (A.shape[0], 1))
    return np.sum(np.sum(A * idx_i * idx_j))

%timeit numpy_f3(A)

174 µs ± 10.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


现在向量化的版本的速度提高了约120倍（不同计算机上此数值可能不同）。 为了使$A[i，j] * i * j$的计算过程可向量化，我们构造了两个新的二维数组idx_i和idx_j，它们的形状与数组A相同，其中的元素为数组A的元素所对应的索引号值。如之前所讲的，尺寸相同的数组间的加减乘除是向量化操作。

我们甚至可以通过使用`broadcasting`使代码更好。 “ idx_i”和“ idx_j”是2D数组，分别由列和行中的重复向量组成。 因此，我们不必构造两个二维数组“ idx_i”和“ idx_j”，只需要构造两个一维数组即可，因为NumPy自动使用broadcasting的操作将它们变为二维数组。请参考下面代码：

In [93]:
def numpy_f3_bd(A):
    idx_i = np.arange(A.shape[0])[:, np.newaxis]
    idx_j = np.arange(A.shape[1])
    return np.sum(np.sum(A * idx_i * idx_j))

%timeit numpy_f3_bd(A)

68.1 µs ± 3.62 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


更好的版本意味着：额外的〜1.5倍性能提升和更少的代码。

很明显，向量化可以在许多情况下能提高计算性能。直接的代码实现一般在逻辑上更清晰，代码也更容易实现，但却降低了计算效率。如果计算速度是重要的关心点，则首先尝试重新考虑和重构问题，找到逻辑上可能复杂但代码速度更高的替代方法。然后，如有可能，优化代码的特定部分（函数，循环等）使代码更优。

------

### More reading
* [Scipy lectures - NumPy](https://www.scipy-lectures.org/intro/numpy/index.html)
* [NumPy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)
* [From Python to NumPy](https://github.com/rougier/from-python-to-numpy)